import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === 'production';

esbuild.build({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
}).catch(() => process.exit(1));

function compileTypeScriptFiles() {
  const directories = ['services', 'ui', 'models', 'utils'];
  
  directories.forEach(dir => {
    const srcDir = path.join(process.cwd(), 'src', dir);
    const distDir = path.join(process.cwd(), 'dist', dir);
    
    if (!fs.existsSync(srcDir)) return;
    
    if (!fs.existsSync(distDir)) {
      fs.mkdirSync(distDir, { recursive: true });
    }
    
    const files = fs.readdirSync(srcDir);
    let compiledCount = 0;
    
    files.forEach(file => {
      if (file.endsWith('.ts')) {
        const srcFile = path.join(srcDir, file);
        const outFile = path.join(distDir, file.replace('.ts', '.js'));
        
        esbuild.buildSync({
          entryPoints: [srcFile],
          bundle: false,
          format: 'cjs',
          target: 'es2018',
          logLevel: 'error',
          sourcemap: prod ? false : 'inline',
          outfile: outFile,
        });
        
        compiledCount++;
      }
    });
    
    if (compiledCount > 0) {
      console.log(`✓ Compiled ${compiledCount} TypeScript files in ${dir}/`);
    }
  });
}

// 等待主文件编译完成后，编译子目录
setTimeout(() => {
  compileTypeScriptFiles();
}, 100);